server:
  port: 8080
spring:
  application:
    name: KAFKA-MESSAGING-BROKER
  datasource:
    url: jdbc:mariadb://localhost:3306/kafka_service
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect




